### ISSUE TITLE
Speaker Directory

### ISSUE THREAD

**Issue by theophani** [janl/waaa#22]
A lot of people have expressed interested in a speaker directory to either be attached to this project, or to be some how affiliated or endorsed. Let’s work out a solution that can be self-service for both speakers and curators.

Discuss!

/cc  @chiuki

**Comment by mairead** [comment]
Off the top of my head I'm assuming it would have a sign up form, with basic contact details and maybe a skills or expertise selector that could then be represented as a tag list. Maybe a place to link to existing slide decks and to list previous events spoken at

I read one article where the conference curators were using video as part of their selection process which they said was essential and made it difficult for them to do blind selection. So perhaps an opportunity to embed a youtube/video link

Is anything else essential functionality for speakers to communicate about themselves? 

And then I guess the listings would be searchable by name and by specialism/expertise

**Comment by theophani** [comment]
What you describe have been done many times over, the best version being @Lanyrd. @chiuki had the idea that @lanyrd is all set up to have a Speakers Directory with a few caveats:

1) they don't actually list speakers anywhere yet at all and do not provide a way search for speakers or filter them.
2) “people” in their system either have an existing speaking engagement, or they don't, and so there is no way to announce yourself being interested in being a speaker.
3) your areas of expertise come from the tags attached to your existing speaking engagements, and you can’t add additional potential speaking topics.

I’d love to engage @Lanyrd in a conversation about how feasible it is to extend their work or build upon an API before trying to build a collection that completes with their already amazing setup and wealth of data.

**Comment by mairead** [comment]
yes absolutely, being able to tie in to an existing industry network would be invaluable. I hadn't thought of using someone elses data. So could we be of help providing a filtering or search functionality? I'm not sure what lanyrd expose at the moment.

**Comment by mairead** [comment]
Faq says API in pipeline. Have emailed them to see if they can give us a release data or a peek at their specs.

**Comment by theophani** [comment]
@mairead re contacting @lanyrd about their API: :+1:

**Comment by chiuki** [comment]
Did @lanyrd respond? The speaker directory works much better as a part of Lanyrd, but we shouldn't wait for them unless they gave us specific ETA.

We can use Twitter as login so that the ids will match those on Lanyrd for future import.

As a start, each speaker profile should have:
- Name
- Photo (grabbed from Twitter)
- How to contact (Twitter? Email?)
- Location
- Topics as tag list (mobile, web, android, javascript, career etc)
- Link to external speaker profile

People can browse by topic as they are looking for potential speakers. Filter by location will be great too, but that could be tricky to implement. Guess we can store the lat lng and do a simple bounding box query.

**Comment by mairead** [comment]
No sadly no response from Lanyrd. I did just read a post from Simon Willison on the google group, saying they had been aiming for Dec last year so probably not far off. 

How to we proceed from here? How would you like to split up the tasks?

**Comment by chiuki** [comment]
I'm afraid I don't have time to contribute at this time :(

**Comment by theophani** [comment]
The desired speaker directory now exists!
http://articulate-network.lanyrd.com/speakers/

**Comment by theophani** [comment]
I have added the Articulate Network link to the curators section: https://github.com/janl/waaa/commit/e94536802c9bee72bfdc3e5253de162498b09f74
