### ISSUE TITLE
OKCon 2013 Call for Proposals

### ISSUE THREAD

**Issue by beatricemartini** [janl/waaa#23]
Hi!

We know each other, I'm Beatrice from OpenTechSchool! Apart from that, I am also the curator of OKCon 2013 – Open Knowledge Conference and I'd like to invite all followers of We Are All Awesome to submit their proposals – we _just_ launched our Call!

http://okcon.org/call-for-proposals/

Would you like the idea to add it to your resources/ hints to potential female speakers?
In any case, thank you for your kind attention.

Best,
Beatrice

**Comment by theophani** [comment]
Hey, I wanted to close this but realized that I never explained why I did not respond before: I decided to direct people to [@CallbackWomen](https://twitter.com/callbackwomen) instead of maintaining a list here, since the information there is always fresh.
